name: getsops
description: Install SOPS

inputs:
  version:
    description: sops version
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Install SOPS
      uses: jaxxstorm/action-install-gh-release@71d17cb091aa850acb2a1a4cf87258d183eb941b # v1.11.0
      with:
        repo: getsops/sops
        tag: ${{ inputs.version }}
        cache: enable
        extension-matching: disable
        rename-to: sops
        chmod: 0755
